#!/usr/bin/env python
if __name__ == '__main__':
  import sys
  import os
  sys.path.insert(0, os.path.abspath('config'))
  import configure
  configure_options = [
    'PETSC_ARCH=cray-gnu-shared',
    '--with-cc=cc',
    '--with-cxx=CC',
    '--with-fc=ftn',
    '--with-fortran-datatypes=0',
    '--with-fortran-interfaces=0',
    '--CFLAGS=-march=corei7-avx -fopenmp -O3 -ffast-math ',
    '--CXXFLAGS=-march=corei7-avx -fopenmp -O3 -ffast-math ',
    '--FFLAGS= -march=corei7-avx -fopenmp -O3 -ffast-math ',

    '--known-bits-per-byte=8',
    '--known-level1-dcache-assoc=0',
    '--known-level1-dcache-linesize=32',
    '--known-level1-dcache-size=32768',
    '--known-memcmp-ok=1',
    '--known-mpi-c-double-complex=1',
    '--known-mpi-int64_t=0',
    '--known-mpi-long-double=1',
    '--known-mpi-shared-libraries=0',
    '--known-sizeof-MPI_Comm=4',
    '--known-sizeof-MPI_Fint=4',
    '--known-sizeof-char=1',
    '--known-sizeof-double=8',
    '--known-sizeof-float=4',
    '--known-sizeof-int=4',
    '--known-sizeof-long-long=8',
    '--known-sizeof-long=8',
    '--known-sizeof-short=2',
    '--known-sizeof-size_t=8',
    '--known-sizeof-void-p=8',
#     '--with-ar=ar',
#     '--with-ranlib=ranlib',
#     '--with-scalar-type=real',
#     '--with-shared-ld=ar',

    '--with-debugging=0',
    '--with-shared-libraries=1',
    '--with-threadcomm=1',
    '--with-openmp=1',
    '--with-pthreadclasses=1',
    '--download-triangle',
    '--download-ctetgen',
    '--download-chaco',
    '--download-superlu',
    '--download-superlu_dist',
    '--download-ml',
    '--with-make-np=12',

    '--with-hypre-dir=/opt/cray/tpsl/1.4.1/GNU/49/sandybridge',
    '--with-hypre=1',
    '--with-metis-dir=/opt/cray/tpsl/1.4.1/GNU/49/sandybridge',
    '--with-metis=1',
    '--with-mumps-dir=/opt/cray/tpsl/1.4.1/GNU/49/sandybridge',
    '--with-mumps=1',
    '--with-parmetis-dir=/opt/cray/tpsl/1.4.1/GNU/49/sandybridge',
    '--with-parmetis=1',
    '--with-ptscotch-dir=/opt/cray/tpsl/1.4.1/GNU/49/sandybridge',
    '--with-ptscotch=1',
    '--with-scalapack-dir=/opt/cray/libsci/13.0.1/GNU/49/sandybridge',
    '--with-scalapack=1',
    '--with-sundials-dir=/opt/cray/tpsl/1.4.1/GNU/49/sandybridge',
    '--with-sundials=1',
#     '--with-superlu-dir=/opt/cray/tpsl/1.4.1/GNU/49/sandybridge',
#     '--with-superlu=1',
#     '--with-superlu_dist-dir=/opt/cray/tpsl/1.4.1/GNU/49/sandybridge',
#     '--with-superlu_dist=1',
  ]
  configure.petsc_configure(configure_options)
